# data_server_addr = "0.0.0.0:8081"
data_server_enabled = false
ticket_server_cors_allow_headers = "All"
ticket_server_cors_allow_methods = "All"
# ticket_server_cors_allow_credentials = true # this should be disabled
ticket_server_addr = "0.0.0.0:8080"
ticket_server_cors_allow_origins = "All"
# ticket_server_cert = "/certs/fullchain.pem"
# ticket_server_key = "/certs/privkey.pem"

[[resolvers]]
regex = ".*"
substitution_string = "archive/$0"

[resolvers.storage]
url = "http://s3:9000"
response_scheme = "http" 

[resolvers.allow_guard]
allow_reference_names = "All"
allow_fields = "All"
allow_tags = "All"
allow_formats = [
    "BAM",
    "CRAM",
    "VCF",
    "BCF",
]
allow_classes = [
    "body",
    "header",
]

