data_server_addr = "0.0.0.0:8081"
ticket_server_addr = "0.0.0.0:8080"
ticket_server_cors_allow_origins = "All"
ticket_server_cert = "/certs/fullchain.pem"
ticket_server_key = "/certs/privkey.pem"

[[resolvers]]
#regex = "([^/]+)/(.*)"
regex = "(.*)"
substitution_string = "$1"

[resolvers.storage]
bucket = "EGAD74900000101"
endpoint = "http://download:8443/s3/"
path_style = true

#[[resolvers]]
#regex = "(.*)"
#substitution_string = "$0"
#
#[resolvers.storage]
#bucket = 'archive'
#endpoint = "http://s3:9000/"
