# data_server_addr = "0.0.0.0:8081"
data_server_enabled = false
ticket_server_cors_allow_headers = "All"
ticket_server_cors_allow_methods = "All"
# ticket_server_cors_allow_credentials = true # this should be disabled
ticket_server_addr = "0.0.0.0:8080"
ticket_server_cors_allow_origins = "All"
ticket_server_cert = "/certs/download.pem"
ticket_server_key = "/certs/download-key.pem"

[[resolvers]]
regex = ".*"
substitution_string = "s3/https://doi.example/ty009.sfrrss/600.45asasga/data/$0"

[resolvers.storage]
url = "https://localhost:8443"
response_scheme = "https"
forward_headers = true

[resolvers.allow_guard]
allow_reference_names = "All"
allow_fields = "All"
allow_tags = "All"
allow_formats = [
    "BAM",
    "CRAM",
    "VCF",
    "BCF",
]
allow_classes = [
    "body",
    "header",
]
