ticket_server_addr = "0.0.0.0:8080"
ticket_server_cors_allow_origins = "All"
ticket_server_cert = "/certs/download.pem"
ticket_server_key = "/certs/download-key.pem"

data_server_enabled = false

[[resolvers]]
regex = ".*"
substitution_string = "$0"

[resolvers.storage]
url = "https://download:8443/"
response_scheme = "https"
